"""add therapist schedule overrides

Revision ID: bae89f464254
Revises: a5a20f46ae8a
Create Date: 2026-09-23 20:23:17.911033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae89f464254'
down_revision: Union[str, Sequence[str], None] = 'a5a20f46ae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('slot_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_schedule_overrides_id'), 'therapist_schedule_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_therapist_schedule_overrides_override_date'), 'therapist_schedule_overrides', ['override_date'], unique=False)
    op.create_index(op.f('ix_therapist_schedule_overrides_therapist_id'), 'therapist_schedule_overrides', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_therapists_is_active'), 'therapists', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapists_is_active'), table_name='therapists')
    op.drop_index(op.f('ix_therapist_schedule_overrides_therapist_id'), table_name='therapist_schedule_overrides')
    op.drop_index(op.f('ix_therapist_schedule_overrides_override_date'), table_name='therapist_schedule_overrides')
    op.drop_index(op.f('ix_therapist_schedule_overrides_id'), table_name='therapist_schedule_overrides')
    op.drop_table('therapist_schedule_overrides')
    # ### end Alembic commands ###
